### ISSUE TITLE
v1.5.0 and 1.6.0 not working in module environment

### ISSUE THREAD

**Issue by Amareis** [enisdenjo/graphql-http#6]
**Screenshot**
![image](https://user-images.githubusercontent.com/4806617/189673737-67824c35-3ec5-4b64-b9d9-4f2ea34d6d5f.png)

**Expected Behaviour**
I expected it to works :)

**Actual Behaviour**
but instead it did _this_.

**Debug Information**
Just install latest version and used it with vite.

**Further Information**
Obviously, something is wrong with bunling - in lib folder there is no `audits.mjs`, so it should be `audits/index.mjs` in reexport

**Comment by enisdenjo** [comment]
Oh right, I fixed it with https://github.com/enisdenjo/graphql-http/commit/cae269a53b3f609901556706aba61907a64496c7 but haven't released it. 😅

**Comment by Amareis** [comment]
> Oh right, I fixed it with [cae269a](https://github.com/enisdenjo/graphql-http/commit/cae269a53b3f609901556706aba61907a64496c7) but haven't released it. sweat_smile

It seems to still be wrong, since it should handles mjs files and not a js

**Comment by enisdenjo** [comment]
@Amareis I've just released a new version, can you please try with [v1.6.1](https://github.com/enisdenjo/graphql-http/releases/tag/v1.6.1)?

**Comment by Amareis** [comment]
Ah, ok, 1.6.1 is working. So, 10 minutes from bug-report to fix, that a speed!
